# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


## Environment Properties
minecraft_version=1.19.2
minecraft_version_range=[1.19.2,1.20)
forge_version=43.5.0
forge_version_range=[43,)
loader_version_range=[43,)
mapping_channel=official
mapping_version=1.19.2


## Mod Properties
mod_id=sophiesbettertables
mod_name=Sophie's Better Tables
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.sophiecheese
mod_authors=Bentcheesee
mod_description=Revamps loot tables and recipes with various mods and even base Minecraft itself!
